[package]
name = "winp-sys"
description = "Read outputs of the process for Windows"
version = "0.1.0"
authors = ["bnuts <beehive.nuts@gmail.com>"]
license = "MIT"
links = "winp"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
